Update keyPath to ceil(maxLvl/8),add chck len(key)
vocdoni/arbo pull request #21
Opened 2021-09-30 15:55 UTC by arnaucube

Update keyPath to be ceil(maxLevels/8), add check of key len on Add,
AddBatch, Update, GenProof, Get.

2021-10-04 11:45 UTC, ed255 requested changes

2021-10-04 11:45 UTC, ed255 commented on tree.go
> +	keyPath := make([]byte, len(siblings))
why not `keyPathFromKey(len(siblings, k))` here?

2021-10-04 11:45 UTC, ed255 commented on tree.go
> +	maxKeyLen := int(math.Ceil(float64(maxLevels) / float64(8))) //nolint:gomnd
Since you're using the ceiling here, you could find collisions when maxLevels is not a multiple of 8, and you have a len(key) == maxKeyLen where the last bits differ.  Is that a problem?  A quick solution I can think of is to force the maxLevels to be a multiple of 8.  The other solution is to validate that the trailing bits in the key are 0.

2021-10-05 13:48 UTC, arnaucube commented on tree.go
> +	keyPath := make([]byte, len(siblings))
Because it would give an error, as the siblings does not contain an element for each level of maxLevels, it contains the siblings until the leaf (which does might not be at the maximum depth of the tree).

2021-10-05 13:57 UTC, arnaucube commented on tree.go
> +	maxKeyLen := int(math.Ceil(float64(maxLevels) / float64(8))) //nolint:gomnd
I've created a new issue (https://github.com/vocdoni/arbo/issues/22) with your comment, referencing to this original comment, so can be done in a near-future iteration.

2021-10-05 14:15 UTC, arnaucube commented on tree.go
> +	keyPath := make([]byte, len(siblings))
One thing that is not related to this but that I thought now when reviewing the `CheckProof` code is: https://github.com/vocdoni/arbo/issues/23

2021-10-05 15:38 UTC, ed255 commented on tree.go
> +	keyPath := make([]byte, len(siblings))
I see.  Then shouldn't it be `keyPath := make([]byte, len(siblings)/8)`?

2021-10-05 15:51 UTC, ed255 approved these changes

2021-10-05 16:08 UTC, merged